---
controller:
  config:
    use-proxy-protocol: true
  service:
    annotations:
      service.beta.kubernetes.io/scw-loadbalancer-proxy-protocol-v2: "true"
      service.beta.kubernetes.io/scw-loadbalancer-use-hostname: "true"
      service.beta.kubernetes.io/scw-loadbalancer-zone: ${zone}
    externalTrafficPolicy: Local
    loadBalancerIP: ${ip_adress}
  metrics:
    enabled: true
    serviceMonitor:
      additionalLabels:
        release: prometheus
      enabled: true
  # extraArgs:
  #   enable-ssl-passthrough: "true"
