##
## Configuration settings that directly affect the Velero deployment YAML.
##

# Details of the container image to use in the Velero deployment & daemonset (if
# enabling node-agent). Required.
image:
  repository: velero/velero
  tag: v1.11.0

initContainers:
  # - name: velero-plugin-for-csi
  #   image: velero/velero-plugin-for-csi:v0.5.0
  #   imagePullPolicy: IfNotPresent
  #   volumeMounts:
  #     - mountPath: /target
  #       name: plugins
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.7.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

configuration:
  # Parameters for the BackupStorageLocation(s). Configure multiple by adding other element(s) to the backupStorageLocation slice.
  # See https://velero.io/docs/v1.6/api-types/backupstoragelocation/
  backupStorageLocation:
    # name is the name of the backup storage location where backups should be stored. If a name is not provided,
    # a backup storage location will be created with the name "default". Optional.
  - name: default
    # provider is the name for the backup storage location provider. If omitted
    # `configuration.provider` will be used instead.
    provider: aws
    # bucket is the name of the bucket to store backups in. Required.
    bucket: ${velero_s3_bucket_name}
    # Additional provider-specific configuration. See link above
    # for details of required/optional fields for your provider.
    config: {
      region: "${velero_s3_bucket_region}",
      s3ForcePathStyle: true,
      s3Url: "${velero_s3_bucket_endpoint}"
    }

# Backup schedules to create.
# Eg:
schedules:
  daily-backup:
    disabled: false
    labels:
      # TODO: Compléter ceci
      myenv: nginx
    annotations:
      # TODO: Compléter ceci
      myenv: nginx
    schedule: "0 0 * * *"
    useOwnerReferencesInBackup: false
    template:
      ttl: "240h"
      storageLocation: default
      includedNamespaces:
      # TODO: Compléter ceci
      - nginx
