version: '3.4'
services:
  tf-scaleway:
    image: hashicorp/terraform:1.5.7
    user: ${DOCKER_USER:-1000}
    working_dir: /app/scaleway
    environment:
      # Without this value, the Helm provider fails to fetch chart repository data
      - XDG_CACHE_HOME=/tmp
      #
    volumes:
      - ./scaleway:/app/scaleway
      - ./common:/app/common
  tf-ovh:
    image: hashicorp/terraform:1.5.7
    user: ${DOCKER_USER:-1000}
    working_dir: /app/ovh
    environment:
      # Without this value, the Helm provider fails to fetch chart repository data
      - XDG_CACHE_HOME=/tmp
      #
    volumes:
      - ./ovh:/app/ovh
      - ./common:/app/common
  tf-standalone:
    image: hashicorp/terraform:1.5.7
    user: ${DOCKER_USER:-1000}
    working_dir: /app/standalone
    environment:
      # Without this value, the Helm provider fails to fetch chart repository data
      - XDG_CACHE_HOME=/tmp
      #
    volumes:
      - ./standalone:/app/standalone
      - ./common:/app/common
  tf-bucket-ovh:
    image: hashicorp/terraform:1.5.7
    user: ${DOCKER_USER:-1000}
    working_dir: /app/state_bucket
    environment:
      # Without this value, the Helm provider fails to fetch chart repository data
      - XDG_CACHE_HOME=/tmp
      - AWS_ACCESS_KEY_ID="no_need_to_define_an_access_key"
      - AWS_SECRET_ACCESS_KEY="no_need_to_define_a_secret_key"
    volumes:
      - ./state_bucket:/app/state_bucket
  bash:
    image: bash
    user: ${DOCKER_USER:-1000}
    working_dir: /app
  argocd-cli:
    image: argoproj/argocd:v2.6.15
    user: ${DOCKER_USER:-1000}
  kubectld:
    image: bitnami/kubectl:1.31.2
    user: ${DOCKER_USER:-1000}
    working_dir: /app
    volumes:
      - ./vault/.kube:/app/.kube