apiVersion: v1
kind: Secret
metadata:
  name: secret-helm
type: Opaque
data:
  secret1: {{ .Values.secret1 | b64enc }}
  {{- if .Values.secret2 }}
  secret2: {{ .Values.secret2 | b64enc }}
  {{- end }}
  {{- if .Values.secret3 }}
  secret3: {{ .Values.secret3 | b64enc }}
  {{- end }}