grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: ${issuer}
    labels: {}
    path: /
    pathType: Prefix

    hosts:
      - ${hostname}
    tls:
      - secretName: ${hostname}
        hosts:
          - ${hostname}
