grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: ${issuer}
    labels: {}
    path: /
    pathType: Prefix

    hosts:
      - ${hostname}
    tls:
      - secretName: ${hostname}
        hosts:
          - ${hostname}
  adminPassword: ${grafana_admin_password}
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          url: http://loki-gateway.loki.svc.cluster.local
  persistence:
    enabled: ${grafana_persistence_enabled}
    persistence:
      size: ${grafana_persistence_size}

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "k8s"
          orgId: 1
          options:
            path: /var/lib/grafana/dashboards/k8s
  dashboards:
    k8s:
      nginx:
        url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/grafana/dashboards/nginx.json
        datasource: Prometheus
      request-handling-performance:
        url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/grafana/dashboards/request-handling-performance.json
        datasource: Prometheus
      k8s-system-api-server:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
        datasource: Prometheus
      k8s-system-coredns:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json
        datasource: Prometheus
      k8s-views-global:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
        datasource: Prometheus
      k8s-views-namespaces:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
        datasource: Prometheus
      k8s-views-nodes:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
        datasource: Prometheus
      k8s-views-pods:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
        datasource: Prometheus
  grafana.ini:
    dashboards:
      default_home_dashboard_path: /var/lib/grafana/dashboards/k8s/k8s-views-global.json
prometheus:
  prometheusSpec:
  %{ if prometheus_persistence_enabled }
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: ${prometheus_persistence_size}
    %{ endif }
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
